/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nb_robot_xf_TtsNative */

#ifndef _Included_com_nb_robot_xf_TtsNative
#define _Included_com_nb_robot_xf_TtsNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nb_robot_xf_TtsNative
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_nb_robot_xf_TtsNative_hello
  (JNIEnv *, jobject);

/*
 * Class:     com_nb_robot_xf_TtsNative
 * Method:    login
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_nb_robot_xf_TtsNative_login
  (JNIEnv *, jobject);

/*
 * Class:     com_nb_robot_xf_TtsNative
 * Method:    logout
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_nb_robot_xf_TtsNative_logout
  (JNIEnv *, jobject);

/*
 * Class:     com_nb_robot_xf_TtsNative
 * Method:    runTts
 * Signature: (Ljava/lang/String;Ljava/lang/String;III)I
 */
JNIEXPORT jint JNICALL Java_com_nb_robot_xf_TtsNative_runTts
  (JNIEnv *, jobject, jstring, jstring, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
