#!/bin/bash
# bankrobot server
#
# description: run bankrobot server after startup

case $1 in
    start)
        /bin/bash /usr/local/bin/bankrobot-start.sh
    ;;
    stop)
        /bin/bash /usr/local/bin/bankrobot-stop.sh
    ;;
    restart)
        /bin/bash /usr/local/bin/bankrobot-stop.sh
        /bin/bash /usr/local/bin/bankrobot-start.sh
    ;;
esac
exit 0
